name: Python API CI/CD

# Controls when the workflow should run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your desired Python version, e.g., '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # The command you confirmed: pip install -r requirements.txt

      # Step 4: Run basic checks (replace with your actual testing command if needed)
      - name: Run Linting / Basic Checks
        # This is a placeholder; in a real project, you'd run 'pytest' or 'flake8' here
        run: |
          echo "Running basic checks..."
          # Example: pytest

    
      - name: Deployment Instructions Placeholder
        run: |
          echo "Build and Test passed. Deployment to Crane Cloud needs further setup (Docker/cranecloud-cli)."
